# Generated by Django 5.2.3 on 2025-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
